CREATE DATABASE IF NOT EXISTS Proxecto02;
USE Proxecto02;
CREATE TABLE FABRICA(
	id_fabrica INT NOT NULL,
	nombre VARCHAR(30) ,
	direccion VARCHAR(50),
	ciudad VARCHAR (25),
	pais VARCHAR (15),
	PRIMARY KEY (id_fabrica)
);
CREATE TABLE COCHE(
	id_coche INT NOT NULL ,
	matricula VARCHAR(7) UNIQUE NOT NULL,
	color VARCHAR(10),
	anho INTEGER,
	modelo VARCHAR(20),
	id_fabricacion INTEGER,
	disponibilidad BOOLEAN,
	imagen VARCHAR(255),
	PRIMARY KEY (id_coche)
);
CREATE TABLE EMPLEADO(
	id_empleado INT NOT NULL ,
	NIF VARCHAR(9) NOT NULL,
	nombre VARCHAR(70) NOT NULL ,
	usuario VARCHAR (15),
	contrasenha VARCHAR (255),
	salario FLOAT,
	mail VARCHAR(50),
	telefono VARCHAR(12),
	puesto VARCHAR(20),
	direccion VARCHAR(50),
	PRIMARY KEY (id_empleado)
);
CREATE TABLE CLIENTE(
	id_cliente INT NOT NULL ,
	NIF VARCHAR(9) NOT NULL,
	nombre VARCHAR(70) NOT NULL ,
	telefono VARCHAR(12),
	mail VARCHAR(50),
	PRIMARY KEY (id_cliente)	
);
CREATE TABLE ALQUILA(
	id_alquiler INT NOT NULL AUTO_INCREMENT,
	fecha_alquiler DATE,
	fecha_devolucion DATE,
	id_coche INT,
	id_cliente INT,
	id_empleado INT,
	PRIMARY KEY (id_alquiler)
);

CREATE TABLE VENTA(
	id_venta INT NOT NULL AUTO_INCREMENT,
	fecha_venta DATE,
	id_coche INT,
	id_cliente INT,
	id_empleado INT,
	PRIMARY KEY (id_venta)
);

ALTER TABLE VENTA ADD CONSTRAINT K_VENTA_COCHE FOREIGN KEY (id_coche) REFERENCES COCHE(id_coche) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE VENTA ADD CONSTRAINT K_VENTA_TRABAJADOR FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE VENTA ADD CONSTRAINT K_VENTA_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE COCHE ADD CONSTRAINT K_COCHE_FABRICA FOREIGN KEY (id_fabricacion) REFERENCES FABRICA(id_fabrica) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ALQUILA ADD CONSTRAINT K_ALQUILA_COCHE FOREIGN KEY (id_coche) REFERENCES COCHE(id_coche) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ALQUILA ADD CONSTRAINT K_ALQUILA_TRABAJADOR FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ALQUILA ADD CONSTRAINT K_ALQUILA_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente) ON UPDATE CASCADE ON DELETE RESTRICT;




