/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.Alquileres;

import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dam2_alu05@inf.ald
 */
public class TablaAlquileresJDialog extends javax.swing.JDialog {

    /**
     * Creates new form TablaAlquileresJDialog
     */
    public TablaAlquileresJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlquileresLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlquileresTable = new javax.swing.JTable();
        NuevoAlquilerButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        clockBean1 = new clock.ClockBean();
        BorrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AlquileresLabel.setFont(new java.awt.Font("Inter Regular", 1, 24)); // NOI18N
        AlquileresLabel.setText("Alquileres");

        AlquileresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Vendedor", "Nombre Cliente", "Matricula", "Fecha Alquiler", "Fecha Devolucion"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false, false,
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

        }
    );
    jScrollPane1.setViewportView(AlquileresTable);

    NuevoAlquilerButton.setText("Nuevo Alquiler");
    NuevoAlquilerButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            NuevoAlquilerButtonActionPerformed(evt);
        }
    });

    CancelarButton.setText("Cancelar");
    CancelarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CancelarButtonActionPerformed(evt);
        }
    });

    BorrarButton.setText("Borrar");
    BorrarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BorrarButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(26, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(AlquileresLabel)
                    .addGap(277, 277, 277)
                    .addComponent(NuevoAlquilerButton))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BorrarButton)
                        .addComponent(CancelarButton)))
                .addComponent(clockBean1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(NuevoAlquilerButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(AlquileresLabel)
                    .addGap(5, 5, 5)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(BorrarButton)
                    .addGap(18, 18, 18)
                    .addComponent(CancelarButton))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
            .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoAlquilerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoAlquilerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoAlquilerButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarButtonActionPerformed

     public void addRowTable(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.AlquileresTable.getModel();
        model.addRow(row);
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.AlquileresTable.getModel();
        model.setRowCount(0);
        AlquileresTable.clearSelection();
        AlquileresTable.revalidate();
        AlquileresTable.repaint();
    }

    public void addNuevoAlquilerMenuItemListener(ActionListener al) {
        this.NuevoAlquilerButton.addActionListener(al);
    }

    public void addCancelarAlquilerMenuItemListener(ActionListener al) {
        this.CancelarButton.addActionListener(al);
    }

    public void addBorrarButtonMenuItemListener(ActionListener al){
        this.BorrarButton.addActionListener(al);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlquileresLabel;
    private javax.swing.JTable AlquileresTable;
    private javax.swing.JButton BorrarButton;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JButton NuevoAlquilerButton;
    private clock.ClockBean clockBean1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
