/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.NuevoCliente;

import java.awt.event.ActionListener;
import view.Alquileres.NuevoAlquilerJDialog;
import view.Ventas.NuevaVentaJDialog;

/**
 *
 * @author alumno
 */
public class NuevoClienteJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoClienteJDialog.class.getName());

    /**
     * Creates new form NuevoClienteJDialog
     */
    public NuevoClienteJDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevoClienteLabel = new javax.swing.JLabel();
        NIFLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        TelefonoLabel = new javax.swing.JLabel();
        MailLabel = new javax.swing.JLabel();
        NifTextField = new javax.swing.JTextField();
        NombreTextField = new javax.swing.JTextField();
        TelefonoTextField = new javax.swing.JTextField();
        MailTextField = new javax.swing.JTextField();
        AceptarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        clockBean1 = new clock.ClockBean();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NuevoClienteLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NuevoClienteLabel.setText("Crear Nuevo Cliente");

        NIFLabel.setText("NIF :");

        NombreLabel.setText("Nombre :");

        TelefonoLabel.setText("Telefono :");

        MailLabel.setText("Mail :");

        AceptarButton.setText("Aceptar");

        CancelarButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NuevoClienteLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NIFLabel)
                                .addGap(18, 18, 18)
                                .addComponent(NifTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NombreLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(MailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(MailTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TelefonoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TelefonoTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(AceptarButton)
                                .addGap(18, 18, 18)
                                .addComponent(CancelarButton)))
                        .addGap(44, 44, 44)
                        .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(NuevoClienteLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIFLabel)
                    .addComponent(NifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLabel)
                    .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoLabel)
                    .addComponent(TelefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MailLabel)
                    .addComponent(MailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarButton)
                    .addComponent(CancelarButton))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getNif() {
        return this.NifTextField.getText();
    }

    public String getNombre() {
        return this.NombreTextField.getText();
    }

    public String getTelefono() {
        return this.TelefonoTextField.getText();
    }

    public String getMail() {
        return this.MailTextField.getText();
    }

    public void addNuevoClienteItemListener(ActionListener al) {
        this.AceptarButton.addActionListener(al);
    }

    public void addCancelarMenuItemListener(ActionListener al) {
        this.CancelarButton.addActionListener(al);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JLabel MailLabel;
    private javax.swing.JTextField MailTextField;
    private javax.swing.JLabel NIFLabel;
    private javax.swing.JTextField NifTextField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JLabel NuevoClienteLabel;
    private javax.swing.JLabel TelefonoLabel;
    private javax.swing.JTextField TelefonoTextField;
    private clock.ClockBean clockBean1;
    // End of variables declaration//GEN-END:variables
}
