/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu05@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.notLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        LogoLabel = new javax.swing.JLabel();
        clockBean1 = new clock.ClockBean();
        EditButton = new javax.swing.JButton();
        NuevaContraseñaPasswordField = new javax.swing.JPasswordField();
        jMenuBar2 = new javax.swing.JMenuBar();
        VentaMenu = new javax.swing.JMenu();
        ventajMenuItem = new javax.swing.JMenuItem();
        AlquilerMenu = new javax.swing.JMenu();
        AlquilerMenuItem = new javax.swing.JMenuItem();
        CochesMenu = new javax.swing.JMenu();
        cochesMenuItem = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(179, 179, 179));

        LoginButton.setText("Login");

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/logo_bmw_editado.png"))); // NOI18N

        EditButton.setText("Cambiar Contraseña");

        NuevaContraseñaPasswordField.setToolTipText("Introduce la nueva Contraseña");

        VentaMenu.setText("Ventas");

        ventajMenuItem.setText("Ventas...");
        VentaMenu.add(ventajMenuItem);

        jMenuBar2.add(VentaMenu);

        AlquilerMenu.setText("Alquiler");

        AlquilerMenuItem.setText("Alquileres...");
        AlquilerMenu.add(AlquilerMenuItem);

        jMenuBar2.add(AlquilerMenu);

        CochesMenu.setText("Coches");

        cochesMenuItem.setText("Coches...");
        CochesMenu.add(cochesMenuItem);

        jMenuBar2.add(CochesMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(NuevaContraseñaPasswordField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addGap(23, 23, 23)
                        .addComponent(NuevaContraseñaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoLabel)))
                .addGap(27, 27, 27)
                .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addVentaMenuItemListener(ActionListener al){
        this.VentaMenu.addActionListener(al);
    }
    
    public void addAlquilerMenuItemListener(ActionListener al){
        this.AlquilerMenu.addActionListener(al);
    }
    
    public void addCochesMenuItemListener(ActionListener al ){
        this.CochesMenu.addActionListener(al);
    }
      public void addLoginMenuItemListener(ActionListener al) {
        this.LoginButton.addActionListener(al);
    }
      public void addVentasMenuItemListener(ActionListener al) {
        this.ventajMenuItem.addActionListener(al);
    }
       public void addAlquilerJMenuItemListener(ActionListener al) {
        this.AlquilerMenuItem.addActionListener(al);
    }
       public void addcochesJJMenuItemListener(ActionListener al) {
        this.cochesMenuItem.addActionListener(al);
    }
      public void notLogin(){
          this.AlquilerMenu.setVisible(false);
          this.CochesMenu.setVisible(false);
          this.VentaMenu.setVisible(false);
          this.NuevaContraseñaPasswordField.setVisible(false);
          this.EditButton.setVisible(false);
      }
      public String getNuevaContraseña(){
          return this.NuevaContraseñaPasswordField.getText();
      }
        public void Login(){
          this.AlquilerMenu.setVisible(true);
          this.CochesMenu.setVisible(true);
          this.VentaMenu.setVisible(true);
          this.LoginButton.setVisible(false);
          this.EditButton.setVisible(true);
          this.NuevaContraseñaPasswordField.setVisible(true);
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AlquilerMenu;
    private javax.swing.JMenuItem AlquilerMenuItem;
    private javax.swing.JMenu CochesMenu;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPasswordField NuevaContraseñaPasswordField;
    private javax.swing.JMenu VentaMenu;
    private clock.ClockBean clockBean1;
    private javax.swing.JMenuItem cochesMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem ventajMenuItem;
    // End of variables declaration//GEN-END:variables
}
