/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.Ventas;

import java.awt.event.ActionListener;
import java.time.LocalDate;

/**
 *
 * @author dam2_alu05@inf.ald
 */
public class NuevaVentaJDialog extends javax.swing.JDialog {

    /**
     * Creates new form VentasJDialog
     */
    public NuevaVentaJDialog(TablaVentasJDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentasLabel = new javax.swing.JLabel();
        VendedorTextField = new javax.swing.JTextField();
        VendedorLabel = new javax.swing.JLabel();
        ClienteLabel = new javax.swing.JLabel();
        ClienteTextField = new javax.swing.JTextField();
        MatriculaLabel = new javax.swing.JLabel();
        MatriculaTextField = new javax.swing.JTextField();
        FechaVentaLabel = new javax.swing.JLabel();
        FechaVentaTextField = new javax.swing.JTextField();
        AceptarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        ClienteNuevoButton = new javax.swing.JButton();
        clockBean1 = new clock.ClockBean();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        VentasLabel.setFont(new java.awt.Font("Inter Regular", 1, 24)); // NOI18N
        VentasLabel.setText("Nueva Venta");

        VendedorLabel.setText("Nombre Vendedor:");

        ClienteLabel.setText("Nombre Cliente:");

        MatriculaLabel.setText("Matricula:");

        FechaVentaLabel.setText("Fecha venta:");

        AceptarButton.setText("Aceptar");
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        ClienteNuevoButton.setText("Nuevo Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(AceptarButton)
                .addGap(18, 18, 18)
                .addComponent(ClienteNuevoButton)
                .addGap(18, 18, 18)
                .addComponent(CancelarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VentasLabel)
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClienteLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VendedorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaVentaLabel)
                            .addComponent(MatriculaLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ClienteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(MatriculaTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FechaVentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VentasLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VendedorLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteLabel)
                    .addComponent(ClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaVentaLabel)
                    .addComponent(FechaVentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarButton)
                    .addComponent(ClienteNuevoButton)
                    .addComponent(CancelarButton))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarButtonActionPerformed

    public String getVendedor() {
        return this.VendedorTextField.getText();
    }

    public void setVendedor(String NombreVendedor) {
        this.VendedorTextField.setText(NombreVendedor);
    }

    public String getCliente() {
        return this.ClienteTextField.getText();
    }

    public void setCliente(String NombreCliente) {
        this.ClienteTextField.setText(NombreCliente);
    }

    public String getMatricula() {
        return this.MatriculaTextField.getText();
    }

    public void setMatricula(String Matricula) {
        this.MatriculaTextField.setText(Matricula);
    }

    public LocalDate getFechaVenta() {
        return LocalDate.parse(this.FechaVentaTextField.getText());
    }

    public void SetFechaAlquiler(LocalDate FechaVenta) {
        this.FechaVentaTextField.setText(FechaVenta.toString());
    }
    
    public void AceptarButtonActionListener(ActionListener al){
        this.AceptarButton.addActionListener(al);
    }
    
    public void NuevoClienteButtonActionListener(ActionListener al){
        this.ClienteNuevoButton.addActionListener(al);
    }
    
    public void CancelarButtonActionListener(ActionListener al){
        this.CancelarButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JButton ClienteNuevoButton;
    private javax.swing.JTextField ClienteTextField;
    private javax.swing.JLabel FechaVentaLabel;
    private javax.swing.JTextField FechaVentaTextField;
    private javax.swing.JLabel MatriculaLabel;
    private javax.swing.JTextField MatriculaTextField;
    private javax.swing.JLabel VendedorLabel;
    private javax.swing.JTextField VendedorTextField;
    private javax.swing.JLabel VentasLabel;
    private clock.ClockBean clockBean1;
    // End of variables declaration//GEN-END:variables
}
