/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.Alquileres;

/**
 *
 * @author dam2_alu05@inf.ald
 */
public class NuevoAlquilerJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NuevoAlquilerJDialog
     */
    public NuevoAlquilerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevoAlquilerLabel = new javax.swing.JLabel();
        NombreVendedorLabel = new javax.swing.JLabel();
        NombreClienteLabel = new javax.swing.JLabel();
        MatriculaLabel = new javax.swing.JLabel();
        ModeloLabel = new javax.swing.JLabel();
        FechaAlquilerLabel = new javax.swing.JLabel();
        FechaDevolucionLabel = new javax.swing.JLabel();
        NombreVendedorTextField = new javax.swing.JTextField();
        NombreClienteTextField = new javax.swing.JTextField();
        MatriculaTextField = new javax.swing.JTextField();
        ModeloTextField = new javax.swing.JTextField();
        FechaAlquilerTextField = new javax.swing.JTextField();
        FechaDevolucionTextField = new javax.swing.JTextField();
        AceptarButton = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        NuevoClienteButton = new javax.swing.JButton();
        clockBean1 = new clock.ClockBean();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NuevoAlquilerLabel.setFont(new java.awt.Font("Inter Regular", 1, 24)); // NOI18N
        NuevoAlquilerLabel.setText("Nuevo Alquiler");

        NombreVendedorLabel.setText("Nombre Vendedor :");

        NombreClienteLabel.setText("Nombre Cliente :");

        MatriculaLabel.setText("Maticula :");

        ModeloLabel.setText("Modelo :");

        FechaAlquilerLabel.setText("Fecha Alquiler :");

        FechaDevolucionLabel.setText("Fecha Devolucion :");

        AceptarButton.setText("Aceptar");
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        NuevoClienteButton.setText("Nuevo Cliente");
        NuevoClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaAlquilerLabel)
                    .addComponent(ModeloLabel)
                    .addComponent(NombreClienteLabel)
                    .addComponent(NombreVendedorLabel)
                    .addComponent(MatriculaLabel)
                    .addComponent(FechaDevolucionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AceptarButton)
                        .addGap(18, 18, 18)
                        .addComponent(NuevoClienteButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreVendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaAlquilerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaDevolucionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NuevoAlquilerLabel)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(NuevoAlquilerLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreVendedorLabel)
                    .addComponent(NombreVendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreClienteLabel)
                    .addComponent(NombreClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatriculaLabel)
                    .addComponent(MatriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeloLabel)
                    .addComponent(ModeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaAlquilerLabel)
                    .addComponent(FechaAlquilerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaDevolucionLabel)
                    .addComponent(FechaDevolucionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarButton)
                    .addComponent(Cancelar)
                    .addComponent(NuevoClienteButton)
                    .addComponent(clockBean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarButtonActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void NuevoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoClienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoClienteButtonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel FechaAlquilerLabel;
    private javax.swing.JTextField FechaAlquilerTextField;
    private javax.swing.JLabel FechaDevolucionLabel;
    private javax.swing.JTextField FechaDevolucionTextField;
    private javax.swing.JLabel MatriculaLabel;
    private javax.swing.JTextField MatriculaTextField;
    private javax.swing.JLabel ModeloLabel;
    private javax.swing.JTextField ModeloTextField;
    private javax.swing.JLabel NombreClienteLabel;
    private javax.swing.JTextField NombreClienteTextField;
    private javax.swing.JLabel NombreVendedorLabel;
    private javax.swing.JTextField NombreVendedorTextField;
    private javax.swing.JLabel NuevoAlquilerLabel;
    private javax.swing.JButton NuevoClienteButton;
    private clock.ClockBean clockBean1;
    // End of variables declaration//GEN-END:variables
}
